name: Deploy Python App to DigitalOcean

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set up Docker
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: SSH into server
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} username@${{ secrets.SERVER_IP }} << 'EOF'
          # Check if deploy_to_gcp_app_engine file exists
          if [ ! -f /opt/pythonapp/deploy_to_gcp_app_engine ]; then
            echo "Error: 'deploy_to_gcp_app_engine' file is missing!"
            exit 1
          fi
          
          # Navigate to the app directory
          cd /opt/pythonapp

          # Check if docker-compose.dev.yml file exists
          if [ ! -f docker-compose.dev.yml ]; then
            echo "Error: 'docker-compose.dev.yml' file is missing!"
            exit 1
          fi

          # Build and start Docker containers
          echo "Building Docker containers..."
          sudo docker-compose -f docker-compose.dev.yml up -d

          # Check if the app started successfully
          if [ $(sudo docker ps -q -f name=pythonapp) ]; then
            echo "App deployed successfully!"
          else
            echo "Error: App failed to start!"
            exit 1
          fi
        EOF

    - name: Cleanup
      run: |
        # Add any cleanup steps if necessary
        echo "Deployment completed!"
