name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Cache Docker layers to speed up builds (optional)
      - name: Cache Docker layers
        uses: actions/cache@v3  # Updated version to v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t python-digitalocean-app .

      # Step 5: Run the Docker container (without tests)
      - name: Run Docker container
        run: |
          docker run --rm -e GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} python-digitalocean-app
