name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH private key
      run: |
        echo "${{ secrets.DO_SSH_KEY }}" > private_key
        chmod 600 private_key

    - name: Upload project to server
      run: |
        sudo apt-get update && sudo apt-get install -y rsync
        rsync -az -e "ssh -i private_key -o StrictHostKeyChecking=no" ./ ${{ secrets.DO_SSH_USER }}@${{ secrets.DO_HOST }}:/opt/pythonapp

    - name: Deploy via SSH
      run: |
        echo "Attempting to SSH into the server..."
        ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.DO_SSH_USER }}@${{ secrets.DO_HOST }} << 'EOF'
          echo "Connected to server."
          cd /opt/pythonapp || { echo "Directory /opt/pythonapp not found!"; exit 1; }

          echo "Pulling updated Docker images..."
          docker compose -f docker-compose.dev.yml pull

          echo "Stopping existing containers..."
          docker compose -f docker-compose.dev.yml down

          echo "Starting new containers..."
          docker compose -f docker-compose.dev.yml up -d --build

          echo "Deployment complete."
        EOF