name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SSH and rsync
      run: sudo apt-get update && sudo apt-get install -y openssh-client rsync

    - name: Decode SSH private key
      run: |
        echo "${{ secrets.DO_SSH_KEY_BASE64 }}" | base64 -d > private_key
        chmod 600 private_key

    - name: Rsync files to remote server
      env:
        HOST: ${{ secrets.DO_HOST }}
        USER: ${{ secrets.DO_USER }}
      run: |
        rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" ./ $USER@$HOST:/opt/pythonapp/

    - name: SSH and run remote deploy script
      env:
        HOST: ${{ secrets.DO_HOST }}
        USER: ${{ secrets.DO_USER }}
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
          echo "Connected to server ✅"
          if [ -f "/opt/pythonapp/deploy_to_gcp_app_engine.sh" ]; then
            chmod +x /opt/pythonapp/deploy_to_gcp_app_engine.sh
            /opt/pythonapp/deploy_to_gcp_app_engine.sh
          else
            echo "⚠️ deploy_to_gcp_app_engine.sh not found!"
            exit 1
          fi
        EOF
