name: Build and Deploy Docker App

on:
  push:
    branches:
      - main   # Trigger action on push to the 'main' branch
  pull_request:
    branches:
      - main   # Trigger action on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Cache Docker layers (update to actions/cache@v3)
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t python-digitalocean-app .

      # Run tests (if applicable) - this step can be skipped if not needed
      - name: Run tests
        run: |
          docker run --rm python-digitalocean-app python -m unittest discover -s tests

      # Deploy Docker container and pass the GOOGLE_API_KEY as an environment variable
      - name: Deploy Docker container
        run: |
          docker run -d --name python-digitalocean-app -p 8000:80 \
          -e GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} \
          python-digitalocean-app

      # Optional: Check Docker container status
      - name: Check Docker container status
        run: |
          docker ps
