name: Deploy Python App to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # STEP 1: Setup SSH key
      - name: Setup SSH key
        run: |
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      # STEP 2: Debugging SSH and deploying app
      - name: SSH into server and deploy app
        run: |
          echo "Attempting to SSH into the server..."

          ssh -o StrictHostKeyChecking=no -v -i private_key ${{ secrets.DO_SSH_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            echo "Connected to server."

            echo "Listing files in /opt/pythonapp"
            ls -l /opt/pythonapp

            if [ ! -f /opt/pythonapp/deploy_to_gcp_app_engine ]; then
              echo "Error: 'deploy_to_gcp_app_engine' file is missing!"
              exit 1
            fi

            cd /opt/pythonapp || exit 1

            if [ ! -f docker-compose.dev.yml ]; then
              echo "Error: 'docker-compose.dev.yml' file is missing!"
              exit 1
            fi

            echo "Building Docker containers..."
            sudo docker-compose -f docker-compose.dev.yml up -d

            if [ \$(sudo docker ps -q -f name=pythonapp) ]; then
              echo "App deployed successfully!"
            else
              echo "Error: App failed to start!"
              exit 1
            fi
          EOF

      # STEP 3: Clean up SSH key
      - name: Cleanup
        run: rm -f private_key
