name: Deploy Python App to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up SSH key and known hosts
      - name: Set up SSH key
        run: |
          # Decode the base64 encoded SSH private key stored in the secret
          echo "$DO_SSH_KEY_BASE64" | base64 --decode > private_key
          
          # Set the proper permissions for the private key
          chmod 600 private_key
          
          # Create SSH directory and move the key to the appropriate location
          mkdir -p ~/.ssh
          mv private_key ~/.ssh/id_ed25519
          
          # Add the remote host to known hosts to avoid SSH warnings
          ssh-keyscan -t ed25519 $HOST >> ~/.ssh/known_hosts

      # Install required dependencies (rsync and OpenSSH client)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync openssh-client

      # Deploy files to DigitalOcean server using rsync over SSH
      - name: Deploy files to DigitalOcean
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" ./ $USER@$HOST:/opt/pythonapp/

